### ISSUE TITLE
Make a specific nifti convertor

### ISSUE THREAD

**Issue by simonqueric** [ivadomed/lumbar-classification-rsna-challenge-2024#13]
Issue opened by misclick while NathanMolinier was explaining me how to open an issue from an action task.

**Comment by jcohenadad** [comment]
no issue should be closed without a comment as to why this issue was closed: is it solved? if so by which commit? see github good practice (use google to find more): 
- https://rewind.com/blog/best-practices-for-using-github-issues/
- https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
- https://intranet.neuro.polymtl.ca/onboarding/software-development.html
